"""initial migration

Revision ID: 7015c4db4275
Revises: 
Create Date: 2025-08-23 22:55:09.272200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7015c4db4275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('mock_apis',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Mock接口名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='接口描述'),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=False, comment='HTTP方法'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='接口路径'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('response_headers', sa.JSON(), nullable=True, comment='响应头配置'),
    sa.Column('response_body', sa.JSON(), nullable=True, comment='响应体配置'),
    sa.Column('response_template', sa.Text(), nullable=True, comment='响应模板'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_apis_id'), 'mock_apis', ['id'], unique=False)
    op.create_table('request_logs',
    sa.Column('mock_api_id', sa.Integer(), nullable=True, comment='关联的Mock接口ID'),
    sa.Column('request_method', sa.String(length=10), nullable=False, comment='请求方法'),
    sa.Column('request_path', sa.String(length=500), nullable=False, comment='请求路径'),
    sa.Column('request_headers', sa.JSON(), nullable=True, comment='请求头'),
    sa.Column('request_body', sa.JSON(), nullable=True, comment='请求体'),
    sa.Column('request_params', sa.JSON(), nullable=True, comment='请求参数'),
    sa.Column('response_status_code', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('response_headers', sa.JSON(), nullable=True, comment='响应头'),
    sa.Column('response_body', sa.JSON(), nullable=True, comment='响应体'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='响应时间(毫秒)'),
    sa.Column('client_ip', sa.String(length=45), nullable=True, comment='客户端IP'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User Agent'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mock_api_id'], ['mock_apis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_mock_apis_id'), table_name='mock_apis')
    op.drop_table('mock_apis')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
