"""Initial migration

Revision ID: 9d6468db43a7
Revises:
Create Date: 2025-08-17 23:28:21.030699

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d6468db43a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column(
            "mock_api_id", sa.Integer(), nullable=True, comment="关联的Mock接口ID"
        ),
        sa.Column(
            "request_method", sa.String(length=10), nullable=False, comment="请求方法"
        ),
        sa.Column(
            "request_path", sa.String(length=500), nullable=False, comment="请求路径"
        ),
        sa.Column("request_headers", sa.JSON(), nullable=True, comment="请求头"),
        sa.Column("request_body", sa.JSON(), nullable=True, comment="请求体"),
        sa.Column("request_params", sa.JSON(), nullable=True, comment="请求参数"),
        sa.Column(
            "response_status_code", sa.Integer(), nullable=True, comment="响应状态码"
        ),
        sa.Column("response_headers", sa.JSON(), nullable=True, comment="响应头"),
        sa.Column("response_body", sa.JSON(), nullable=True, comment="响应体"),
        sa.Column(
            "response_time_ms", sa.Integer(), nullable=True, comment="响应时间(毫秒)"
        ),
        sa.Column("client_ip", sa.String(length=45), nullable=True, comment="客户端IP"),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="User Agent"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mock_api_id"],
            ["mock_apis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_logs_id"), "request_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_logs_id"), table_name="request_logs")
    op.drop_table("request_logs")
    # ### end Alembic commands ###
