"""add_categories_table

Revision ID: ce1ba19a5322
Revises: 9d6468db43a7
Create Date: 2025-08-22 21:03:12.047367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1ba19a5322'
down_revision = '9d6468db43a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('mock_apis', sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'))
    op.create_foreign_key(None, 'mock_apis', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mock_apis', type_='foreignkey')
    op.drop_column('mock_apis', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
